-- Seed Sample Properties

INSERT INTO properties (
  address,
  city,
  state,
  zip_code,
  price,
  arv,
  equity_percentage,
  property_type,
  bedrooms,
  bathrooms,
  sqft,
  status,
  description,
  features
) VALUES 
(
  '1234 Pacific Coast Hwy',
  'Newport Beach',
  'CA',
  '92660',
  1250000,
  1650000,
  32,
  'SFR',
  4,
  3,
  2850,
  'active',
  'Stunning coastal property with ocean views. Prime location for flip or luxury rental.',
  ARRAY['Ocean Views', 'Updated Kitchen', 'Pool', 'Guest House']
),
(
  '5678 Beach Blvd',
  'Huntington Beach',
  'CA',
  '92648',
  3400000,
  4500000,
  28,
  'Multi-Family',
  NULL,
  NULL,
  12000,
  'active',
  '8-unit multifamily in prime Huntington Beach location. Strong rental history.',
  ARRAY['8 Units', 'Parking', 'Laundry Facility', 'Corner Lot']
),
(
  '9012 Westminster Ave',
  'Westminster',
  'CA',
  '92683',
  890000,
  1200000,
  35,
  'SFR',
  3,
  2,
  1850,
  'active',
  'Great flip opportunity in growing area. Needs cosmetic updates.',
  ARRAY['Large Lot', 'RV Parking', 'Original Owner', 'Good Schools']
),
(
  '3456 Main Street',
  'Orange',
  'CA',
  '92868',
  5800000,
  7500000,
  29,
  'Commercial',
  NULL,
  NULL,
  25000,
  'active',
  'Prime commercial building in downtown Orange. NNN tenants in place.',
  ARRAY['Triple Net', 'Corner Location', 'Parking Structure', 'Updated HVAC']
);
